import { gzipSync } from 'bun'

const built = await Bun.build({ entrypoints: [`${import.meta.dir}/../src/player/main.ts`], target: 'browser', minify: true, splitting: false })
if (!built.success || built.outputs.length !== 1) throw new AggregateError(built.logs, 'Player bundle failed')
const styled = await Bun.build({ entrypoints: [`${import.meta.dir}/../src/player/style.css`], target: 'browser', minify: true })
if (!styled.success || styled.outputs.length !== 1) throw new AggregateError(styled.logs, 'Player styles failed')
const [script, css] = await Promise.all([built.outputs[0]!.text(), styled.outputs[0]!.text()])
const raw = new TextEncoder().encode(script + css), compressed = gzipSync(raw).length
// A measured ceiling for this implementation, enforced in CI to catch bundle growth.
if (raw.length > 110_000 || compressed > 30_000) throw new Error(`Player exceeds size budget: ${raw.length} raw / ${compressed} gzip bytes`)
const output = `// Generated by bun run build:player. Do not edit.\nexport const playerAssets = ${JSON.stringify({ script, css })}\n`
const destination = `${import.meta.dir}/../generated/player.ts`
if (process.argv.includes('--check')) {
  if (await Bun.file(destination).text() !== output) throw new Error('Player bundle is stale. Run bun run build:player.')
} else await Bun.write(destination, output)
console.log(`Included player: ${raw.length} bytes (${compressed} gzip); no runtime dependencies.`)
